### ISSUE TITLE
InvalidOperationException on master

### ISSUE THREAD

**Issue by N3X15** [KeenSoftwareHouse/SpaceEngineers#304]
```
2015-06-22 15:48:01.548 - Thread:  10 ->  Exception occured: System.InvalidOperationException: Message registration failed, message type: UpdatePilotRelativeEntryMsg, message id: 9922 ---> System.TypeInitializationException: The type initializer for 'VRage.Serialization.BlitSerializer`1' threw an exception. ---> System.InvalidOperationException: Type 'Sandbox.Game.Multiplayer.MySyncShipController+UpdatePilotRelativeEntryMsg' is not blittable ---> System.ArgumentException: Object contains non-primitive or non-blittable data.
   at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle..ctor(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle.Alloc(Object value, GCHandleType type)
   at VRage.Library.Utils.MyLibraryUtils.ThrowNonBlittable[T]()
   --- End of inner exception stack trace ---
   at VRage.Library.Utils.MyLibraryUtils.ThrowNonBlittable[T]()
   at VRage.Serialization.BlitSerializer`1..ctor()
   at VRage.Serialization.BlitSerializer`1..cctor()
   --- End of inner exception stack trace ---
   at Sandbox.Game.Multiplayer.MySyncLayer.CreateBlittable[TMsg]() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 190
   at Sandbox.Game.Multiplayer.MySyncLayer.GetSerializer[TMsg]() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 161
   at Sandbox.Game.Multiplayer.MySyncLayer.<>c__DisplayClassa`2.<RegisterEntityMessage>b__9(MySyncLayer layer) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 144
   at Sandbox.Game.Multiplayer.MySyncLayer.<>c__DisplayClass1`1.<RegisterMessage>b__0(MySyncLayer layer) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 125
   at Sandbox.Game.Multiplayer.MySyncLayer.Registrator`1.Register(MySyncLayer layer) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayerCallback.cs:line 83
   --- End of inner exception stack trace ---
   at Sandbox.Game.Multiplayer.MySyncLayer.Registrator`1.Register(MySyncLayer layer) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayerCallback.cs:line 90
   at Sandbox.Game.Multiplayer.MySyncLayer.RegisterGameEvents() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 72
   at Sandbox.Game.World.MySession.LoadDataComponents(Boolean registerEvents) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\World\MySession.cs:line 612
   at Sandbox.Game.World.MySession.Start(String name, String description, String password, MyObjectBuilder_SessionSettings settings, List`1 mods, Args generationArgs) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\World\MySession.cs:line 1032
   at Sandbox.Game.Gui.MyGuiScreenWorldSettings.<StartNewSandbox>b__6() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Screens\MyGuiScreenWorldSettings.cs:line 780
   at Sandbox.Graphics.GUI.MyGuiScreenBase.RunLoadingAction() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Graphics\Gui\MyGuiScreenBase.cs:line 250
   at Sandbox.Game.Gui.MyGuiScreenLoading.RunLoad() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Screens\MyGuiScreenLoading.cs:line 284
   at Sandbox.Game.Gui.MyGuiScreenLoading.Update(Boolean hasFocus) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Screens\MyGuiScreenLoading.cs:line 243
   at Sandbox.Graphics.GUI.MyScreenManager.Update(Int32 totalTimeInMS) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Graphics\MyScreenManager.cs:line 550
   at Sandbox.Graphics.GUI.MyDX9Gui.Update(Int32 totalTimeInMS) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\GUI\GuiSandbox\MyDX9Gui.cs:line 614
   at Sandbox.Graphics.GUI.MyGuiSandbox.Update(Int32 totalTimeInMS) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\GUI\GuiSandbox\MyGuiSandbox.cs:line 203
   at Sandbox.MySandboxGame.Update() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\MySandboxGame.cs:line 1377
   at Sandbox.Engine.Platform.Game.UpdateInternal() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Engine\Platform\Game.cs:line 156
   at Sandbox.Engine.Platform.Game.RunSingleFrame() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Engine\Platform\Game.cs:line 130
   at Sandbox.Engine.Platform.FixedRenderLoop.<>c__DisplayClass2.<Run>b__1() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Engine\Platform\FixedRenderLoop.cs:line 69
   at Sandbox.Engine.Platform.GenericRenderLoop.Run(VoidAction tickCallback) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Engine\Platform\GenericRenderLoop.cs:line 21
   at Sandbox.Engine.Platform.FixedRenderLoop.Run(VoidAction tickCallback) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Engine\Platform\FixedRenderLoop.cs:line 35
   at Sandbox.Engine.Platform.Game.RunLoop() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Engine\Platform\Game.cs:line 125
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\MySandboxGame.cs:line 307
   at SpaceEngineers.MyProgram.RunInternal(String[] args)
   at SpaceEngineers.MyProgram.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
2015-06-22 15:48:01.548 - Thread:  10 ->  InnerException: 
2015-06-22 15:48:01.548 - Thread:  10 ->  Exception occured: System.TypeInitializationException: The type initializer for 'VRage.Serialization.BlitSerializer`1' threw an exception. ---> System.InvalidOperationException: Type 'Sandbox.Game.Multiplayer.MySyncShipController+UpdatePilotRelativeEntryMsg' is not blittable ---> System.ArgumentException: Object contains non-primitive or non-blittable data.
   at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle..ctor(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle.Alloc(Object value, GCHandleType type)
   at VRage.Library.Utils.MyLibraryUtils.ThrowNonBlittable[T]()
   --- End of inner exception stack trace ---
   at VRage.Library.Utils.MyLibraryUtils.ThrowNonBlittable[T]()
   at VRage.Serialization.BlitSerializer`1..ctor()
   at VRage.Serialization.BlitSerializer`1..cctor()
   --- End of inner exception stack trace ---
   at Sandbox.Game.Multiplayer.MySyncLayer.CreateBlittable[TMsg]() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 190
   at Sandbox.Game.Multiplayer.MySyncLayer.GetSerializer[TMsg]() in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 161
   at Sandbox.Game.Multiplayer.MySyncLayer.<>c__DisplayClassa`2.<RegisterEntityMessage>b__9(MySyncLayer layer) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 144
   at Sandbox.Game.Multiplayer.MySyncLayer.<>c__DisplayClass1`1.<RegisterMessage>b__0(MySyncLayer layer) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayer.cs:line 125
   at Sandbox.Game.Multiplayer.MySyncLayer.Registrator`1.Register(MySyncLayer layer) in c:\Users\Rob\Documents\Projects\SpaceEngineers\Sources\Sandbox.Game\Game\Multiplayer\MySyncLayerCallback.cs:line 83
2015-06-22 15:48:01.548 - Thread:  10 ->  InnerException: 
2015-06-22 15:48:01.548 - Thread:  10 ->  Exception occured: System.InvalidOperationException: Type 'Sandbox.Game.Multiplayer.MySyncShipController+UpdatePilotRelativeEntryMsg' is not blittable ---> System.ArgumentException: Object contains non-primitive or non-blittable data.
   at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle..ctor(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle.Alloc(Object value, GCHandleType type)
   at VRage.Library.Utils.MyLibraryUtils.ThrowNonBlittable[T]()
   --- End of inner exception stack trace ---
   at VRage.Library.Utils.MyLibraryUtils.ThrowNonBlittable[T]()
   at VRage.Serialization.BlitSerializer`1..ctor()
   at VRage.Serialization.BlitSerializer`1..cctor()
2015-06-22 15:48:01.548 - Thread:  10 ->  InnerException: 
2015-06-22 15:48:01.548 - Thread:  10 ->  Exception occured: System.ArgumentException: Object contains non-primitive or non-blittable data.
   at System.Runtime.InteropServices.GCHandle.InternalAlloc(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle..ctor(Object value, GCHandleType type)
   at System.Runtime.InteropServices.GCHandle.Alloc(Object value, GCHandleType type)
   at VRage.Library.Utils.MyLibraryUtils.ThrowNonBlittable[T]()
```

Commit: 6b28b3a00b225ea307fe7b4f6cbb2228814cce9c

**Comment by N3X15** [comment]
I am an idiot, disregard.
