### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by nicolas-f** [KeenSoftwareHouse/SpaceEngineers#541]
When loading this world:

http://steamcommunity.com/sharedfiles/filedetails/?id=706206023

The game crash with the following exception

```

2016-06-18 10:16:42.758 - Thread: 1 -> Exception occured: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
at Sandbox.Engine.Voxels.Planet.MyHeightmapFace.Get4Row(Int32 linearOfft, Single* values, UInt16* map)
at Sandbox.Engine.Voxels.MyPlanetShapeProvider.CalculateCacheCell(MyHeightmapFace map, Cell* cell, Boolean compouteBounds)
at Sandbox.Engine.Voxels.MyPlanetShapeProvider.GetValueForPositionCacheless(Int32 face, Vector2& texcoord, Vector3& localNormal)
at Sandbox.Engine.Voxels.MyPlanetShapeProvider.ProjectToSurface(Vector3 localPos, Vector3& surface)
at Sandbox.Game.Entities.MyPlanet.GetClosestSurfacePointLocal(Vector3& localPos)
at Sandbox.Game.Entities.MyPlanet.GetClosestSurfacePointGlobal(Vector3D& globalPos)
at SpaceEngineers.AI.MySpaceFaunaComponent.SpawnBot(SpawnInfo spawnInfo, MyPlanet planet, MyPlanetAnimalSpawnInfo animalSpawnInfo)
at SpaceEngineers.AI.MySpaceFaunaComponent.UpdateAfterSimulation()
at Sandbox.Game.World.MySession.UpdateComponents()
at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
at Sandbox.MySandboxGame.Update()
at Sandbox.Engine.Platform.Game.UpdateInternal()
at Sandbox.Engine.Platform.Game.RunSingleFrame()
at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
at Sandbox.Engine.Platform.Game.RunLoop()
at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
at SpaceEngineers.MyProgram.Main(String[] args)
2016-06-18 10:16:42.759 - Thread: 1 -> Hiding window
2016-06-18 10:16:43.258 - Thread: 1 -> Hiding window done
2016-06-18 10:16:43.258 - Thread: 1 -> Showing message
2016-06-18 10:16:43.280 - Thread: 1 -> ERROR: branch name cannot be resolved, services=
2016-06-18 10:16:43.280 - Thread: 1 -> ERROR: branch name cannot be resolved, services=
2016-06-18 10:16:43.280 - Thread: 1 -> ERROR: branch name cannot be resolved, services=
```

**Comment by nicolas-f** [comment]
I'm using the dev branch

**Comment by lord-devious** [comment]
Please use the forum for bug reports. These issues are only for the GitHub contributors, Keen doesn't read these.

http://forums.keenswh.com/forums/bug-reports.326950/

**Comment by lord-devious** [comment]
That bug has already been reported several times, by the way :smile:

**Comment by nicolas-f** [comment]
Thanks for the answer
