### ISSUE TITLE
Space Engineers Crashing on startup

### ISSUE THREAD

**Issue by Annon9007723** [KeenSoftwareHouse/SpaceEngineers#582]
I found this error while trying to open the game. 
2017-05-25 15:26:12.166 - Thread:  26 ->  Exception occured: System.NullReferenceException: Object reference not set to an instance of an object.
   at VRage.Render11.Resources.MyPersistentResource`2.OnDeviceEnd()
   at VRage.Render11.Resources.MyPersistentResourceManager`2.OnDeviceEnd()
   at VRage.Render11.Common.MyGeneralManager.OnDeviceEnd()
   at VRageRender.MyRender11.OnDeviceEnd()
   at VRageRender.MyRender11.DisposeDevice()
   at VRageRender.MyRender11.CreateDeviceInternalSafe(IntPtr windowHandle, MyRenderDeviceSettings settings, MyRenderExceptionEnum& exceptionType)
   at VRageRender.MyRender11.CreateDevice(IntPtr windowHandle, Nullable`1 settingsToTry)
   at VRageRender.MyDX11Render.CreateDevice(IntPtr windowHandle, Nullable`1 settings, MyAdapterInfo[]& adaptersList)
   at VRageRender.ExternalApp.MyRenderThread.RenderThreadStart(Object param)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Is there any way I can fix this? 
Full error report down below
[SpaceEngineers.txt](https://github.com/KeenSoftwareHouse/SpaceEngineers/files/1030374/SpaceEngineers.txt)

**Comment by kapitanov** [comment]
👍 
I have the very same issue with both Space Engineers and Medieval Engineers.
Tried reinstalling, tried to delete AppData folder, tried to update video drivers, but issue still remains.

Full logs are here
[SpaceEngineers.log.txt](https://github.com/KeenSoftwareHouse/SpaceEngineers/files/1066408/SpaceEngineers.log.txt)
[VRageRender-DirectX11.log.txt](https://github.com/KeenSoftwareHouse/SpaceEngineers/files/1066409/VRageRender-DirectX11.log.txt)
